sudo: required

language: generic

services:
  - docker

script:
  - docker build -f rails5.2/camaleon2.4.4.5/Dockerfile -t wpayne/camaleon-docker:rails5.2-cama2.4.4.5 .

after-success:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push wpayne/camaleon-docker
  